feat: change exa to eza

diff --git a/init b/init
--- a/init
+++ b/init
@@ -1,17 +1,17 @@
 #!/bin/bash
 
-COMMANDS=(zsh stow git curl unzip bat exa fzf fd rg)
+COMMANDS=(zsh stow git curl unzip bat eza fzf fd rg)
 
 check_cmd() {
-  command -v "$1" > /dev/null 2>&1
+	command -v "$1" >/dev/null 2>&1
 }
 
 main() {
-  for cmd in "${COMMANDS[@]}"; do
-      if ! check_cmd $cmd; then
-        printf 'check failed, command `%s` not found.\n' $cmd
-      fi
-  done
+	for cmd in "${COMMANDS[@]}"; do
+		if ! check_cmd $cmd; then
+			printf 'check failed, command `%s` not found.\n' $cmd
+		fi
+	done
 }
 
 main
